2021-01-02 14:13:20,409 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
2021-01-02 14:14:17,743 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
2021-01-02 14:15:00,099 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
2021-01-02 14:15:31,947 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
2021-01-02 14:56:42,312 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
2021-01-02 14:56:47,544 ERROR: Exception on /index [GET] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/Users/mazzeogeorge/Code/Flask/tut/app/main/routes.py", line 29, in before_app_request
    db.session.commit()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 320, in __call__
    fn(*args, **kw)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/models.py", line 120, in after_commit
    for obj in session._changes['add']:
NameError: name 'session' is not defined
2021-01-02 14:57:49,623 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
2021-01-02 14:57:52,297 ERROR: Exception on /index [GET] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/Users/mazzeogeorge/Code/Flask/tut/app/main/routes.py", line 29, in before_app_request
    db.session.commit()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 320, in __call__
    fn(*args, **kw)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/models.py", line 120, in after_commit
    for obj in session._changes['add']:
NameError: name 'session' is not defined
2021-01-02 14:58:14,709 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
2021-01-02 14:58:18,658 ERROR: Exception on /index [GET] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/Users/mazzeogeorge/Code/Flask/tut/app/main/routes.py", line 30, in before_app_request
    g.search_form = SearchForm()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/main/forms.py", line 12, in __init__
    kwargs['formdata'] = requenst.args
NameError: name 'requenst' is not defined
2021-01-02 14:59:11,819 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:82]
