2020-12-31 14:15:15,198 ERROR: Exception on /reset_password_request [POST] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/email.py", line 15, in send_password_reset_email
    sender=app.config['ADMINS'][0],
IndexError: string index out of range
2020-12-31 14:15:51,507 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:16:22,415 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MiwiZXhwIjoxNjA5NDQyNzU4LjI4MjUxOH0.t0-cMqncvEcDy5c8LYCBS7_YSo1DkRXvebC0pPpc2Uk [GET] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/routes.py", line 188, in reset_password
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
2020-12-31 14:17:02,240 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:28:22,757 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:32:46,109 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:37:13,616 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
