2020-12-30 13:30:30,139 ERROR: Exception on /user/Bob [GET] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/routes.py", line 89, in user
    page = request.args.get('page',t,type=int)
NameError: name 't' is not defined
2020-12-30 13:30:47,406 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:46]
2020-12-30 13:30:49,365 ERROR: Exception on /user/Bob [GET] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/routes.py", line 100, in user
    next_url=next_url, prev_url=prev_url, form=form)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/mazzeogeorge/Code/Flask/tut/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/mazzeogeorge/Code/Flask/tut/app/templates/user.html", line 35, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-12-30 13:32:38,833 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:46]
2020-12-30 15:00:42,852 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:46]
2020-12-30 19:04:10,910 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-30 19:13:59,589 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:10:53,138 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:11:52,860 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:12:11,158 ERROR: Exception on /reset_password_request [POST] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/email.py", line 13, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/mazzeogeorge/Code/Flask/tut/app/models.py", line 70, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp':time() + expires_in},
NameError: name 'self' is not defined
2020-12-31 14:13:09,310 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:13:13,329 ERROR: Exception on /reset_password_request [POST] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/email.py", line 13, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/mazzeogeorge/Code/Flask/tut/app/models.py", line 70, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp':time() + expires_in},
NameError: name 'self' is not defined
2020-12-31 14:14:07,776 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
2020-12-31 14:14:17,962 ERROR: Exception on /reset_password_request [POST] [in /Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mazzeogeorge/Code/Flask/tut/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
  File "/Users/mazzeogeorge/Code/Flask/tut/app/email.py", line 13, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/mazzeogeorge/Code/Flask/tut/app/models.py", line 71, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
NameError: name 'self' is not defined
2020-12-31 14:15:07,267 INFO: Microblog startup [in /Users/mazzeogeorge/Code/Flask/tut/app/__init__.py:48]
